Traceback (most recent call last):
  File "/home/runner/transbot/venv/lib/python3.8/site-packages/async_google_trans_new/main.py", line 184, in translate
    s.proxy = self.proxies.get("https")
AttributeError: '_RequestContextManager' object has no attribute 'proxy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 24, in interaction_create
    result = await g.translate(content, "ja")
  File "/home/runner/transbot/venv/lib/python3.8/site-packages/async_google_trans_new/main.py", line 241, in translate
    await s.close()
TypeError: object NoneType can't be used in 'await' expression
